### ISSUE TITLE
Struct sort key

### ISSUE THREAD

**Issue by mihai-varga** [weld-project/weld#347] opened 2018-04-25 13:08 UTC
Hello,
It seems that the sort key can't be a struct, the following code returns: `Sort key function must have scalar return type`
```
|x:vec[i32]| sort(x, |n| {n, n})
```
The docs say that structs are in fact supported, so maybe it's just the check here that's outdated?
https://github.com/weld-project/weld/blob/b6ef6748cec3f2740032df164fbeff0aeb0b236a/weld/llvm.rs#L3461

**Comment by sppalkia** [comment] 2019-05-21 23:38
Duplicate of #418 (which is resolved)

**Closed by sppalkia** 2019-05-21 23:38 UTC
